name: firefox
version: "70.0.1"
summary: Mozilla Firefox web browser
description:  Firefox is a powerful, extensible web browser with support for modern web application technologies.
confinement: strict
grade: stable
base: core18

apps:
  firefox:
    command: firefox
    extensions: [ gnome-3-28 ]
    environment:
      DISABLE_WAYLAND: 1
      HOME: "$SNAP_USER_COMMON"
    common-id: com.mozilla.firefox
    slots:
      - dbus-daemon
    plugs:
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - home
      - joystick
      - network
      - network-observe
      - opengl
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - u2f-devices
      - unity7
      - upower-observe
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  firefox:
    plugin: dump
    source: https://archive.mozilla.org/pub/firefox/releases/70.0.1/linux-x86_64/en-GB/firefox-70.0.1.tar.bz2
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      - libasound2
      - libpulse0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
      - ffmpeg
      - libc-bin
      - locales-all
      - libcurl3-gnutls
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libblkid1
      - libbz2-1.0
      - libc6
      - libcairo-gobject2
      - libdb5.3
      - libepoxy0
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - libgtk-3-0
      - liblz4-1
      - liblzma5
      - libmount1
      - libncursesw5
      - libpcre3
      - libselinux1
      - libstdc++6
      - libsystemd0
      - libtinfo5
      - libudev1
      - libuuid1
      - libxcomposite1
      - zlib1g

  xdg-open:
    after: [firefox]
    plugin: nil
    source: .
    override-build: |
      snapcraftctl build
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      install -m 644 mimeapps.list $SNAPCRAFT_PART_INSTALL/usr/share/applications
      update-desktop-database -v $SNAPCRAFT_PART_INSTALL/usr/share/applications
    build-packages:
      - desktop-file-utils


  shared-mime-info:
    after: [xdg-open]
    plugin: nil
    stage-packages:
      - shared-mime-info
      - libblkid1
      - libc6
      - libgcc1
      - liblzma5
      - libmount1
      - libpcre3
      - libselinux1
      - libstdc++6
      - libuuid1
      - zlib1g
    override-build: |
      snapcraftctl build
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/mine
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.mozilla.firefox
